Algoritmo "Primeira questão de lógica"

Var
 A: inteiro
 B: inteiro
 C: inteiro
 resultadoS: inteiro


Inicio
escreva ("Primeiro número: ")
leia(A)
escreva ("Segundo número: ")
leia(B)
escreva ("Terceiro número: ")
leia(C)

 resultadoS <- A + B
 
 limpatela
 
  escreval ("Resultado da soma: ", resultadoS)
 
 se (resultadoS > C) entao
 escreval ("Soma de A e B é maior que C")
 senao
 escreval ("Soma de A e B é menor que C")
 fimse
 



Fimalgoritmo